import zipfile
import subprocess
import shutil
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parent.parent
DOCS_DIR = PROJECT_ROOT / "docs"
DOWNLOAD_DIR = DOCS_DIR / "download"

DOWNLOAD_DIR.mkdir(exist_ok=True)

# -------------------------
# 1 Generate ZIP
# -------------------------

zip_path = DOWNLOAD_DIR / "regatta-docs.zip"

with zipfile.ZipFile(zip_path, "w", zipfile.ZIP_DEFLATED) as z:
    for md_file in DOCS_DIR.rglob("*.md"):
        z.write(md_file, md_file.relative_to(DOCS_DIR))

print("✔ ZIP created:", zip_path)

# -------------------------
# 2 Generate PDF with MkDocs
# -------------------------

print("📄 Building PDF with MkDocs...")
subprocess.run(["mkdocs", "build"], check=True)

pdf_src = PROJECT_ROOT / "site" / "pdf" / "document.pdf"

if not pdf_src.exists():
    raise FileNotFoundError("PDF was not generated by MkDocs")

# guardar PDF temporal
temp_pdf = PROJECT_ROOT / "document_temp.pdf"
shutil.copyfile(pdf_src, temp_pdf)

print("📄 Temporary PDF saved")

# -------------------------
# 3 Build Zensical site
# -------------------------

print("🌐 Building Zensical site...")
subprocess.run(["zensical", "build"], check=True)

# -------------------------
# 4 Copy PDF to final site
# -------------------------

final_pdf_dir = PROJECT_ROOT / "site" / "pdf"
final_pdf_dir.mkdir(exist_ok=True)

shutil.copyfile(temp_pdf, final_pdf_dir / "document.pdf")

print("📄 PDF added to final site")

# borrar temporal
temp_pdf.unlink()

# -------------------------
# 5 Copy ZIP to final site
# -------------------------

final_download_dir = PROJECT_ROOT / "site" / "download"
final_download_dir.mkdir(exist_ok=True)

shutil.copyfile(zip_path, final_download_dir / "regatta-docs.zip")

print("📦 ZIP added to final site")

print("✅ Documentation build complete")